blog/urls.py
from django.conf.urls import url
from blog.views import add_data, article, detail, edit_post, update_post, json_data, new_url, index, page, simple_login, \
    logout, login, register, form

urlpatterns = [
    url(r'add_data/', add_data),
    url(r'articles/', article),
    url(r'post/(\d+)/', detail),
    url(r'edit_post/', edit_post),
    url(r'update_post/', update_post, name="updatepost"),
    url(r'json_data/', json_data),
    url(r'new_url/', new_url),
    url(r'index/', index, name="index"),
    url(r'page/(\d+)', page, name="page"),
    url(r'simple_login', simple_login, name="simple_login"),
    url(r'logout', logout, name="logout"),
    url(r'login', login, name="login"),
    url(r'register', register, name="register"),
    url(r'form', form, name="form"),
]

sz_myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.views import add_data, article, detail, edit_post, update_post, json_data, new_url, index, page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^captcha/', include('captcha.urls')),


]

blog/models.py
from django.db import models

# Create your models here.

class MyManager(models.Manager):
    def count_title(self, kw):
        return self.filter(title__contains=kw).count()


class NormalManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(excerpt__exact='Secret')


class SecretManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(excerpt__exact='Secret')


class Tag(models.Model):
    name = models.CharField(max_length=100)


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(blank=False)
    views = models.PositiveIntegerField(default=100, null=True)
    created_time = models.DateTimeField(auto_now_add=True, null=True)
    tag = models.ManyToManyField(Tag)
    excerpt = models.CharField(max_length=100, default="Normal")
    my_objects = MyManager()
    normal_objects = NormalManager()
    secret_objects = SecretManager()

    def __str__(self):
        return self.title


class Grade(models.Model):
    name = models.CharField(max_length=100)
    boy_num = models.PositiveIntegerField(default=40)
    girl_num = models.PositiveIntegerField(default=50)

    def __str__(self):
        return self.name


class UserInfo(models.Model):
    username = models.CharField(max_length=100, verbose_name="用户名", db_column="姓名")
    email = models.CharField(max_length=100)
    passwd = models.CharField(max_length=400)

    def __str__(self):
        return self.username


    class Meta:
        verbose_name = "用户信息表"
        verbose_name_plural = "用户信息表"


class Student(models.Model):
    name = models.CharField(max_length=100)
    sex = models.BooleanField(default=True)
    grade = models.ForeignKey(Grade)


class People(models.Model):
    name = models.CharField(max_length=100)


class IDCard(models.Model):
    num = models.CharField(max_length=18)
    people = models.OneToOneField(People, on_delete=models.PROTECT)

blog/forms.py
from captcha.fields import CaptchaField
from django import forms


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True,)
    password = forms.CharField(required=True, min_length=5)
    #error_messages包含验证码错误的信息的一个字典
    myfield = CaptchaField(error_messages={"invalid": "验证码错误"})

blog/views.py
import random

from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from blog.forms import RegisterForm
from blog.models import Post, UserInfo


# Create your views here.
from blog.utils import gen_secret


def add_data(request):
    int_num = random.randrange(10)
    title = "post" + str(int_num)
    body = "body of post" + str(int_num)
    Post.objects.create(title=title, body=body)
    return HttpResponse("add data: %s success" % title)


def article(request):
    # a = 5/0
    post_list = Post.objects.all()
    context = {"post_list": post_list}
    print(post_list)
    return render(request, 'blog/article.html', context=context)


def detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'blog/detail.html', context={"post": post})


def edit_post(request):
    print("path:", request.path)
    print("method:", request.method)
    print("encoding:", request.encoding)
    print("COOKIES:", request.COOKIES)
    print("session:", request.session)
    print("get_host", request.get_host())

    kw = request.GET.get('wd')
    user = request.GET.getlist('user')
    passwd = request.GET.get('passwd')
    print(kw, user, passwd)

    return render(request, 'blog/edit_post.html')


def update_post(request):
    post_id = request.POST.get("post_id")
    new_title = request.POST.get("title")
    new_body = request.POST.get("body")
    print(post_id, new_title, new_body)
    post = Post.objects.get(id=post_id)
    post.title = new_title
    post.body = new_body
    post.save()
    return HttpResponse("Yes")


def json_data(request):
    import json
    data = json.dumps({"user": "even", "passwd": "1234"})
    return HttpResponse(data, content_type="application/json")


def new_url(request):
    return  redirect(reverse('page', args=(10, )))


def index(request):
    username = request.session.get('username')
    post_view = 90
    post_author = "Tom"
    post_body = "Hello, lllllllllllllllllllllll"
    evil_code = "<script>alert('你的电脑中毒了，请下载XXXX')</script>"
    context = {"num_list": [], "username": username, "post_view": post_view, "post_author": post_author, "post_body": post_body, "evil_code":evil_code}

    # 分页逻辑
    post_list = Post.my_objects.all()
    paginator = Paginator(post_list, 3)
    page_range = paginator.page_range
    page = paginator.page(1)
    page_post_list = page.object_list
    context.update({"page": page, "page_range": page_range, "page_post_list": page_post_list})
    return render(request, 'blog/home.html', context=context)


def page(request, num):
    post_list = Post.my_objects.all()
    paginator = Paginator(post_list, 3)
    page_range = paginator.page_range
    page = paginator.page(num)
    page_post_list = page.object_list
    context = {"page": page, "page_range": page_range, "page_post_list": page_post_list}
    return render(request, 'blog/home.html', context=context)


def simple_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        passwd = request.POST.get('passwd')
        print(username, passwd)
        request.session['username'] = username
        resp = HttpResponse("登录成功")
        # resp.set_cookie("username", username, max_age=30)
        return resp
    return render(request, 'blog/simple_login.html')



def logout(request):
    resp = HttpResponse("会话删除成功")
    request.session.clear()
    return resp


def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        passwd = request.POST.get('passwd')
        passwd = gen_secret(passwd)
        print(username, passwd)
        user = UserInfo.objects.filter(username=username).filter(passwd=passwd).last()
        if user:
            request.session['username'] = username
            return HttpResponseRedirect(reverse('blog:index'))
        # request.session['username'] = username
        resp = HttpResponse("密码或者帐号输入错误， 请重新登录！")
        # resp.set_cookie("username", username, max_age=30)
        return resp
    return render(request, 'index.html')


def register(request):
    username = request.POST.get("username")
    email = request.POST.get("email")
    passwd = request.POST.get("passwd")
    passwd_confirm = request.POST.get("passwd_confirm")
    print(username, email, passwd, passwd_confirm)
    if passwd == passwd_confirm:
        passwd = gen_secret(passwd)
        UserInfo.objects.create(username=username, email=email, passwd=passwd)
        return HttpResponseRedirect(reverse("blog:login"))
    return HttpResponse("两次密码输入不一致，请重新输入！")


def form(request):
    if request.method == "POST":
        print(dict(request.POST))
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            return HttpResponse("登录成功")
        return HttpResponse("登录失败，请重新登录！")

    register_form = RegisterForm()
    return render(request, 'blog/form.html', {"register_form": register_form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block title %}
        <title>{{ 基础模板 }}</title>
    {% endblock %}
</head>
<body>
{% include 'nav.html' %}

{% block main %}
    <p>网页的内容！</p>
{% endblock %}

{% include 'foot.html' %}
</body>
</html>

templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章列表页</title>
</head>
<body>
<h1>所有文章</h1>

<ul>
    {% for post in post_list %}
        <a href="/blog/post/{{ post.id }}"><li>{{ post }}</li></a>
    {% endfor %}
    

</ul>
</body>
</html>

templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章详情页</title>
</head>
<body>

标题：{{ post.title }} <br>
文章内容：{{ post.body }} <br>

<a href="/blog/edit_post"><input type="submit" value="修改数据"></a>

</body>
</html>

templates/blog/edit_post.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>修改文章内容</title>
</head>
<body>

<form action="{% url 'blog:updatepost' %}", method="post">
    {% csrf_token %}
    文章id为：<input type="text" name="post_id" id=""> <br>
    标题修改为：<input type="text" name="title" id=""> <br>
    文章内容修改为： <textarea name="body" id="" cols="30" rows="10"></textarea> <br>
    <select name="province">
        <option value="北京">北京</option>
        <option value="上海">上海</option>
        <option value="深圳">深圳</option>
    </select>
    <br>
    <input type="submit" value="提交修改">
</form>


</body>
</html>

templates/blog/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>验证码</title>
</head>
<body>
验证码
<form action="{% url 'blog:form' %}" method="post">
    {% csrf_token %}
    邮箱：{{ register_form.email }} <br>
    密码：{{ register_form.password }} <br>
    验证码：{{ register_form.myfield }} <br>

    <input type="submit" value="登录">
</form>

</body>
</html>

templates/blog/home.html
{% extends 'base.html' %}

{% block title %}
<title>这是Home页的title</title>
{% endblock %}


{% block main %}
<p>这是Home页的内容</p>

    {% if username %}
        <p>欢迎你，{{ username }}</p>
        <a href="{% url 'blog:logout' %}"><button>退出登录</button></a>
    {% else %}
        游客请先登录 <br>
        <a href="{% url 'blog:login' %}">登录</a>
    {% endif %}

    <br>

    <p>分页器</p> <br>
    <ul>
        {% for post in page_post_list %}
            {{ post.title }}  <br>
            <br>
        {% endfor %}

    </ul>



    <nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
        {% if page.has_previous %}
            <a href="{% url 'blog:page' page.previous_page_number %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% else %}
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% endif %}

    </li>
      {% for num in page_range %}
        {% ifequal page.number num  %}
            <li class="active"><a href="{% url 'blog:page' num %}">{{ num }} </a></li>
        {% else %}
            <li><a href="{% url 'blog:page' num %}">{{ num }} </a></li>
        {% endifequal %}
        


    {% endfor %}

    <li>
        {% if page.has_next %}
            <a href="{% url 'blog:page' page.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
        {% else %}
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
        {% endif %}

    </li>
  </ul>
</nav>

{% endblock %}

templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>首页</title>
</head>
<body>

    <!-- HTML的注释 -->
    {# 模板文件的注释 #}
    {% comment %}
    a
    afdaf
    afddda
    {% endcomment %}
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    60%
  </div>
</div>

{% for num in num_list %}
{{ num }}
{% empty %}
    该标签下没有文章！
{% endfor %}

{% if username %}
    <p>欢迎您， {{ username }}</p>
{% else %}
    <p>游客，请先登录</p>
{% endif %}

{% ifequal username "admin" %}
    欢迎管理员
{% else %}
    欢迎你，{{ username }}
{% endifequal %}

{#{{ username|default:"游客"}}#}
{{ post_view|add:2 }}
{{ post_author|lower }}
{{ post_body|truncatechars:4 }}
{{ post_body }}

{{ evil_code|safe }}

</body>
</html>

templates/blog/new_page.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block main %}

{% endblock %}

templates/blog/simple_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>简单登录</title>
</head>
<body>
<form action="{% url 'blog:simple_login' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username" id=""> <br>
    密码：<input type="password" name="passwd" id=""> <br>

    <input type="submit" value="登录">

</form>

</body>
</html>

templates/foot.html
<footer>
    网站底部
</footer>

templates/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="zh" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
    </head>
    <body>
        <div class="container">
            <header>
                <h1>欢迎登陆我的 <span>博客</span></h1>
				<nav class="codrops-demos">
					<span>点击 <strong>"加入我们"</strong> 即可注册</span>
					<a href="index.html" class="current-demo">回到首页</a>
				</nav>
            </header>
            <section>				
                <div id="container_demo" >
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  action="{% url 'blog:login' %}" method="post" autocomplete="on">
                                {% csrf_token %}
                                <h1>登陆</h1> 
                                <p> 
                                    <label for="username" class="uname" data-icon="u" > 用户名 </label>
                                    <input id="username" name="username" required="required" type="text" placeholder="请输入用户名"/>
                                </p>
                                <p> 
                                    <label for="password" class="youpasswd" data-icon="p"> 密码 </label>
                                    <input id="password" name="passwd" required="required" type="password" placeholder="请输入密码" /> 
                                </p>
                                <p class="keeplogin"> 
									<input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" /> 
									<label for="loginkeeping">记住密码</label>
								</p>
                                <p class="login button"> 
                                    <input type="submit" value="登陆" /> 
								</p>
                                <p class="change_link">
									没有账号 ?
									<a href="#toregister" class="to_register">加入我们</a>
								</p>
                            </form>
                        </div>

                        <div id="register" class="animate form">

                            <form  action="{% url 'blog:register' %}" method="post" autocomplete="on">
                                {% csrf_token %}
                                <h1> 注册 </h1>
                                <p> 
                                    <label for="usernamesignup" class="uname" data-icon="u">用户名</label>
                                    <input id="username" name="username" required="required" type="text" placeholder="取个帅气的名字吧" />
                                </p>
                                <p> 
                                    <label for="emailsignup" class="youmail" data-icon="e" > 邮箱</label>
                                    <input id="emailsignup" name="email" required="required" type="email" placeholder="请输入你的邮箱"/> 
                                </p>
                                <p> 
                                    <label for="passwordsignup" class="youpasswd" data-icon="p">密码 </label>
                                    <input id="passwordsignup" name="passwd" required="required" type="password" placeholder="请确认四周无人，捂紧键盘，偷偷输入密码"/>
                                </p>
                                <p> 
                                    <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">确认密码 </label>
                                    <input id="passwordsignup_confirm" name="passwd_confirm" required="required" type="password" placeholder="请确认密码"/>
                                </p>
                                <p class="signin button"> 
									<input type="submit" value="注册"/> 
								</p>
                                <p class="change_link">  
									已有账号 ?
									<a href="#tologin" class="to_register"> 登陆 </a>
								</p>
                            </form>
                        </div>
						
                    </div>
                </div>  
            </section>
        </div>
    </body>
</html>

templates/nav.html
<nav>
    导航蓝
</nav>